# Service to prefetch additional Hebrew months into the coordinator cache.
prefetch:
  name: Prefetch months
  description: Generate and cache additional future Hebrew months.
  fields:
    months_ahead:
      required: false
      selector:
        number:
          min: 1
          max: 36
          unit_of_measurement: months
      default: 6
      description: "How many additional months ahead to calculate."

navigate:
  name: Prefetch and focus a Hebrew month
  fields:
    rosh_chodesh:
      selector:
        text:
      description: "Gregorian date of Rosh Chodesh (YYYY-MM-DD)"
